version: '3'

services:
  nginx:
    image: nginx:1.15
    container_name: yoyaku_proxy
    ports:
      - 8000:80
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  php-fpm:
    build: ./docker/php-fpm
    container_name: yoyaku_app
    volumes:
      - .:/var/www/html
  
  mysql:
    image: mysql:5.7
    container_name: yoyaku_db
    environment:
      MYSQL_DATABASE: laravel_app_db
      MYSQL_ROOT_PASSWORD: pAssw0rd
      MYSQL_USER: laravel_app_user
      MYSQL_PASSWORD: pAssw0rd
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: yoyaku_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=yoyaku_db
      - PMA_USER=root
      - PMA_PASSWORD=pAssw0rd
    links:
      - mysql    
    ports:
      - 9000:80
    volumes:
      - ./docker/phpmyadmin

  redis:
    image: redis:latest
    container_name: yoyaku_cache
    ports:
      - 6379:6379